apiVersion: v1
kind: Service
metadata:
  name: backend-app-service-{{ .Release.Name }}
spec:
  selector:
    app: m5-backend-{{ .Release.Name }}
  ports:
    - name: backend-deployment-{{ .Release.Name }}
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP