apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-{{ .Release.Name }}
  labels:
    app: backend-deployment-{{ .Release.Name }}
    env: production
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      project: m5-backend-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: m5-backend-{{ .Release.Name }}
        project: m5-backend-{{ .Release.Name }}
    spec:
      containers:
        - name: backend-container-{{ .Release.Name }}
          image: {{ .Values.backend.image }}
          ports:
            - containerPort:  {{ .Values.backend.port }}
