apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
  labels:
    app: {{ .Release.Name }}-frontend-deployment
    env: production
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}-m5-project
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}-m5-project
    spec:
      containers:
        - name: {{ .Release.Name }}-frontend-container
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort:  {{ .Values.frontend.port }}