apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service-{{ .Release.Name }}
spec:
  selector:
    app: m5-frontend-{{ .Release.Name }}
  ports:
    - name: frontend-deployment-{{ .Release.Name }}
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort