apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-{{ .Release.Name }}
  labels:
    app: frontend-deployment-{{ .Release.Name }}
    env: production
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      project: m5-frontend-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: m5-frontend-{{ .Release.Name }}
        project: m5-frontend-{{ .Release.Name }}
    spec:
      containers:
        - name: frontend-container-{{ .Release.Name }}
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort:  {{ .Values.frontend.port }}